---
- hosts: localhost  # Run these tasks on the same machine (the GitHub runner)
  connection: local
  tasks:
    
    - name: 1. Apply the Kubernetes Deployment
      # This is the command your manual asked for
      # It tells Kubernetes to create/update the deployment
      command: kubectl apply -f ../kubernetes/deployment.yaml

    - name: 2. Apply the Kubernetes Service
      # This tells Kubernetes to create/update the service
      command: kubectl apply -f ../kubernetes/service.yaml
